parameters:
#    amie_user.example.class: AMiE\UserBundle\Example

services:
    acme_user.registration.form.type:
        class: AMiE\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: acme_user_registration }
    acme_user.form.handler.registration:
            class: AMiE\UserBundle\Form\Handler\RegistrationFormHandler
            arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@fos_user.util.token_generator"]
            scope: request
    acme_user.profile.form.type:
            class: AMiE\UserBundle\Form\Type\ProfileFormType
            tags:
                - { name: form.type, alias: acme_user_profile }
    acme_user.form.handler.profile:
            class: AMiE\UserBundle\Form\Handler\ProfileFormHandler
            arguments: ["@fos_user.profile.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@fos_user.util.token_generator"]
            scope: request