parameters:
#    a_mi_e_entreprises.example.class: AMiE\EntreprisesBundle\Example

services:
#    a_mi_e_entreprises.example:
#        class: %a_mi_e_entreprises.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
